{
 "title": "Home Temperature",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Vivek's Room (First Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:14:B7\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsTempC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Vivek's Room (First Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:14:B7\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHtC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Vivek's Room (First Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:14:B7\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHumi\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Vivek's Room (First Floor)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:14:B7\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHtF\" or r[\"_field\"] == \"tsTempF\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:14:B7\" or r[\"host\"] == \"9C:9C:1F:47:4F:81\" or r[\"host\"] == \"C4:5B:BE:54:D1:52\" or r[\"host\"] == \"E8:DB:84:98:C0:E6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsTempC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Living Room (First Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"E8:DB:84:98:C0:E6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsTempC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Living Room (First Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"E8:DB:84:98:C0:E6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHtC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Living Room (First Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"E8:DB:84:98:C0:E6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHumi\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Living Room (First Floor)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"E8:DB:84:98:C0:E6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHtF\" or r[\"_field\"] == \"tsTempF\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Girls's Room (Ground Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:4F:81\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsTempC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Girls's Room (Ground Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:4F:81\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHtC\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Girls's Room (Ground Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:4F:81\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHumi\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Girls's Room (Ground Floor)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:4F:81\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHtF\" or r[\"_field\"] == \"tsTempF\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:14:B7\" or r[\"host\"] == \"9C:9C:1F:47:4F:81\" or r[\"host\"] == \"C4:5B:BE:54:D1:52\" or r[\"host\"] == \"E8:DB:84:98:C0:E6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHumi\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Bed Room (Second Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"C4:5B:BE:54:D1:52\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHtC\" or r[\"_field\"] == \"tsHtF\" or r[\"_field\"] == \"tsHumi\" or r[\"_field\"] == \"tsTempC\" or r[\"_field\"] == \"tsTempF\" or r[\"_field\"] == \"tsType\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Bed Room (Second Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"C4:5B:BE:54:D1:52\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHtC\" or r[\"_field\"] == \"tsHtF\" or r[\"_field\"] == \"tsHumi\" or r[\"_field\"] == \"tsTempC\" or r[\"_field\"] == \"tsTempF\" or r[\"_field\"] == \"tsType\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Bed Room (Second Floor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"9C:9C:1F:47:14:B7\" or r[\"host\"] == \"9C:9C:1F:47:4F:81\" or r[\"host\"] == \"C4:5B:BE:54:D1:52\" or r[\"host\"] == \"E8:DB:84:98:C0:E6\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHtC\" or r[\"_field\"] == \"tsHtF\" or r[\"_field\"] == \"tsHumi\" or r[\"_field\"] == \"tsTempC\" or r[\"_field\"] == \"tsTempF\" or r[\"_field\"] == \"tsType\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  },
  {
   "title": "Bed Room (Second Floor)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"C4:5B:BE:54:D1:52\")\n  |> filter(fn: (r) => r[\"_field\"] == \"tsHtF\" or r[\"_field\"] == \"tsTempF\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {}
   ]
  }
 ]
}